exception in epoch1exception in epoch1
Traceback (most recent call last):
  File "c:\Users\83549\Github Projects\Radiogenemics--on-Ivy-Gap\T1_train.py", line 243, in <module>
    f'{epoch}-{i}_sensitivity=====>>{sensitivity/iters}')
NameError: name 'iters' is not defined

exception in epoch1
Traceback (most recent call last):
  File "c:\Users\83549\Github Projects\Radiogenemics--on-Ivy-Gap\T1_train.py", line 243, in <module>
    f'{epoch}-{i}_sensitivity=====>>{sensitivity/iters}')
NameError: name 'iters' is not defined

exception in epoch1
Traceback (most recent call last):
  File "c:\Users\83549\Github Projects\Radiogenemics--on-Ivy-Gap\T1_train.py", line 257, in <module>
    torchvision.utils.save_image(
  File "C:\Users\83549\anaconda3\envs\PyTorch-gpu\lib\site-packages\torch\autograd\grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\83549\anaconda3\envs\PyTorch-gpu\lib\site-packages\torchvision\utils.py", line 134, in save_image
    ndarr = grid.mul(255).add_(0.5).clamp_(0, 255).permute(1, 2, 0).to('cpu', torch.uint8).numpy()
KeyboardInterrupt

exception in epoch1
Traceback (most recent call last):
  File "c:\Users\83549\Github Projects\Radiogenemics--on-Ivy-Gap\T1_train.py", line 228, in <module>
    trainLossList.list_pushback(trainLoss.item())
KeyboardInterrupt

exception in epoch1
Traceback (most recent call last):
  File "c:\Users\83549\Github Projects\Radiogenemics--on-Ivy-Gap\T1_train.py", line 274, in <module>
    outImage = net(image)
  File "C:\Users\83549\anaconda3\envs\PyTorch-gpu\lib\site-packages\torch\nn\modules\module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "c:\Users\83549\Github Projects\Radiogenemics--on-Ivy-Gap\net.py", line 79, in forward
    L5 = self.c5(self.d4(L4))
  File "C:\Users\83549\anaconda3\envs\PyTorch-gpu\lib\site-packages\torch\nn\modules\module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "c:\Users\83549\Github Projects\Radiogenemics--on-Ivy-Gap\net.py", line 23, in forward
    return self.layer(x)
  File "C:\Users\83549\anaconda3\envs\PyTorch-gpu\lib\site-packages\torch\nn\modules\module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\83549\anaconda3\envs\PyTorch-gpu\lib\site-packages\torch\nn\modules\container.py", line 139, in forward
    input = module(input)
  File "C:\Users\83549\anaconda3\envs\PyTorch-gpu\lib\site-packages\torch\nn\modules\module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\83549\anaconda3\envs\PyTorch-gpu\lib\site-packages\torch\nn\modules\dropout.py", line 100, in forward
    return F.dropout2d(input, self.p, self.training, self.inplace)
  File "C:\Users\83549\anaconda3\envs\PyTorch-gpu\lib\site-packages\torch\nn\functional.py", line 1202, in dropout2d
    return _VF.feature_dropout_(input, p, training) if inplace else _VF.feature_dropout(input, p, training)
RuntimeError: CUDA out of memory. Tried to allocate 16.00 MiB (GPU 0; 6.00 GiB total capacity; 4.42 GiB already allocated; 0 bytes free; 4.47 GiB reserved in total by PyTorch)

exception in epoch1
Traceback (most recent call last):
  File "c:\Users\83549\Github Projects\Radiogenemics--on-Ivy-Gap\T1_train.py", line 274, in <module>
    outImage = net(image)
  File "C:\Users\83549\anaconda3\envs\PyTorch-gpu\lib\site-packages\torch\nn\modules\module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "c:\Users\83549\Github Projects\Radiogenemics--on-Ivy-Gap\net.py", line 79, in forward
    L5 = self.c5(self.d4(L4))
  File "C:\Users\83549\anaconda3\envs\PyTorch-gpu\lib\site-packages\torch\nn\modules\module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "c:\Users\83549\Github Projects\Radiogenemics--on-Ivy-Gap\net.py", line 23, in forward
    return self.layer(x)
  File "C:\Users\83549\anaconda3\envs\PyTorch-gpu\lib\site-packages\torch\nn\modules\module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\83549\anaconda3\envs\PyTorch-gpu\lib\site-packages\torch\nn\modules\container.py", line 139, in forward
    input = module(input)
  File "C:\Users\83549\anaconda3\envs\PyTorch-gpu\lib\site-packages\torch\nn\modules\module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\83549\anaconda3\envs\PyTorch-gpu\lib\site-packages\torch\nn\modules\dropout.py", line 100, in forward
    return F.dropout2d(input, self.p, self.training, self.inplace)
  File "C:\Users\83549\anaconda3\envs\PyTorch-gpu\lib\site-packages\torch\nn\functional.py", line 1202, in dropout2d
    return _VF.feature_dropout_(input, p, training) if inplace else _VF.feature_dropout(input, p, training)
RuntimeError: CUDA out of memory. Tried to allocate 16.00 MiB (GPU 0; 6.00 GiB total capacity; 4.42 GiB already allocated; 0 bytes free; 4.47 GiB reserved in total by PyTorch)

exception in epoch1
Traceback (most recent call last):
  File "c:\Users\83549\Github Projects\Radiogenemics--on-Ivy-Gap\T1_train.py", line 274, in <module>
    outImage = net(image)
  File "C:\Users\83549\anaconda3\envs\PyTorch-gpu\lib\site-packages\torch\nn\modules\module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "c:\Users\83549\Github Projects\Radiogenemics--on-Ivy-Gap\net.py", line 79, in forward
    L5 = self.c5(self.d4(L4))
  File "C:\Users\83549\anaconda3\envs\PyTorch-gpu\lib\site-packages\torch\nn\modules\module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "c:\Users\83549\Github Projects\Radiogenemics--on-Ivy-Gap\net.py", line 23, in forward
    return self.layer(x)
  File "C:\Users\83549\anaconda3\envs\PyTorch-gpu\lib\site-packages\torch\nn\modules\module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\83549\anaconda3\envs\PyTorch-gpu\lib\site-packages\torch\nn\modules\container.py", line 139, in forward
    input = module(input)
  File "C:\Users\83549\anaconda3\envs\PyTorch-gpu\lib\site-packages\torch\nn\modules\module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\83549\anaconda3\envs\PyTorch-gpu\lib\site-packages\torch\nn\modules\dropout.py", line 100, in forward
    return F.dropout2d(input, self.p, self.training, self.inplace)
  File "C:\Users\83549\anaconda3\envs\PyTorch-gpu\lib\site-packages\torch\nn\functional.py", line 1202, in dropout2d
    return _VF.feature_dropout_(input, p, training) if inplace else _VF.feature_dropout(input, p, training)
RuntimeError: CUDA out of memory. Tried to allocate 16.00 MiB (GPU 0; 6.00 GiB total capacity; 4.42 GiB already allocated; 0 bytes free; 4.47 GiB reserved in total by PyTorch)

exception in epoch1
Traceback (most recent call last):
  File "c:\Users\83549\Github Projects\Radiogenemics--on-Ivy-Gap\T1_train.py", line 274, in <module>
    outImage = net(image)
  File "C:\Users\83549\anaconda3\envs\PyTorch-gpu\lib\site-packages\torch\nn\modules\module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "c:\Users\83549\Github Projects\Radiogenemics--on-Ivy-Gap\net.py", line 79, in forward
    L5 = self.c5(self.d4(L4))
  File "C:\Users\83549\anaconda3\envs\PyTorch-gpu\lib\site-packages\torch\nn\modules\module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "c:\Users\83549\Github Projects\Radiogenemics--on-Ivy-Gap\net.py", line 23, in forward
    return self.layer(x)
  File "C:\Users\83549\anaconda3\envs\PyTorch-gpu\lib\site-packages\torch\nn\modules\module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\83549\anaconda3\envs\PyTorch-gpu\lib\site-packages\torch\nn\modules\container.py", line 139, in forward
    input = module(input)
  File "C:\Users\83549\anaconda3\envs\PyTorch-gpu\lib\site-packages\torch\nn\modules\module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\83549\anaconda3\envs\PyTorch-gpu\lib\site-packages\torch\nn\modules\dropout.py", line 100, in forward
    return F.dropout2d(input, self.p, self.training, self.inplace)
  File "C:\Users\83549\anaconda3\envs\PyTorch-gpu\lib\site-packages\torch\nn\functional.py", line 1202, in dropout2d
    return _VF.feature_dropout_(input, p, training) if inplace else _VF.feature_dropout(input, p, training)
RuntimeError: CUDA out of memory. Tried to allocate 16.00 MiB (GPU 0; 6.00 GiB total capacity; 4.42 GiB already allocated; 0 bytes free; 4.47 GiB reserved in total by PyTorch)

exception in epoch1
Traceback (most recent call last):
  File "c:\Users\83549\Github Projects\Radiogenemics--on-Ivy-Gap\T1_train.py", line 274, in <module>
    outImage = net(image)
  File "C:\Users\83549\anaconda3\envs\PyTorch-gpu\lib\site-packages\torch\nn\modules\module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "c:\Users\83549\Github Projects\Radiogenemics--on-Ivy-Gap\net.py", line 79, in forward
    L5 = self.c5(self.d4(L4))
  File "C:\Users\83549\anaconda3\envs\PyTorch-gpu\lib\site-packages\torch\nn\modules\module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "c:\Users\83549\Github Projects\Radiogenemics--on-Ivy-Gap\net.py", line 23, in forward
    return self.layer(x)
  File "C:\Users\83549\anaconda3\envs\PyTorch-gpu\lib\site-packages\torch\nn\modules\module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\83549\anaconda3\envs\PyTorch-gpu\lib\site-packages\torch\nn\modules\container.py", line 139, in forward
    input = module(input)
  File "C:\Users\83549\anaconda3\envs\PyTorch-gpu\lib\site-packages\torch\nn\modules\module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\83549\anaconda3\envs\PyTorch-gpu\lib\site-packages\torch\nn\modules\dropout.py", line 100, in forward
    return F.dropout2d(input, self.p, self.training, self.inplace)
  File "C:\Users\83549\anaconda3\envs\PyTorch-gpu\lib\site-packages\torch\nn\functional.py", line 1202, in dropout2d
    return _VF.feature_dropout_(input, p, training) if inplace else _VF.feature_dropout(input, p, training)
RuntimeError: CUDA out of memory. Tried to allocate 16.00 MiB (GPU 0; 6.00 GiB total capacity; 4.42 GiB already allocated; 0 bytes free; 4.47 GiB reserved in total by PyTorch)

